apiVersion: v2
name: monitoring-umbrella
version: 0.1.0
dependencies:
  - name: k8s-monitoring
    version: 2.0.27
    repository: https://grafana.github.io/helm-charts
  - name: loki
    version: 6.29.0
    repository: https://grafana.github.io/helm-charts
  - name: grafana-operator
    version: 5.17.1
    repository: https://grafana.github.io/helm-charts
